### PR TITLE
Add User Manual

### PR DESCRIPTION
**Pull request by yugaego**
These files are generated and copied from the main company-mode project by 
`$ cd /company-mode/company-mode/doc/`
`$ make install-html`

I don't see a way to avoid duplication of the content, so let me know if you have a better idea.
Supposedly, this semi-automated approach may work fine: all the updates are done on the main repo side. Then in order to publish homepage /manual:
1. make install-html
2. push changes to this repo

### CODE REVIEW

**Comment by dgutov** [comment]
The process looks good to me.

Should I merge this version now?

**Comment by dgutov** [comment]
BTW, here a new documentation project: https://www.emacsdocs.org/

Just in case you haven't seen it yet. Not sure if it's feasible to use as an inspiration here, but maybe we can just offer our manual to be published there someday.

**Comment by yugaego** [comment]
> Should I merge this version now?

Yes, please go ahead. We can add a link from the main page a tiny bit later, after reviewing the manual looks sufficiently fine when published.

> BTW, here a new documentation project: https://www.emacsdocs.org/

Yes, I saw this nice project.

> but maybe we can just offer our manual to be published there someday.

I like this idea.

**Comment by dgutov** [comment]
Thanks!

**Pull request merged**
